version: '3.8'

services:
  postgres:
    image: postgres:latest
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: /run/secrets/db_postgres_password
      POSTGRES_DB: ${DATABASE_NAME}
    secrets:
      - db_postgres_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - ${PG_PORT}:80
    restart: always

secrets:
  db_postgres_password:
    file: ./private/db_postgres_password.txt

volumes:
  pgdata:
    driver: local
